### ISSUE TITLE
test with token and email

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/oda_api#12]

**Comment by burnout87** [comment]
I want  to write some specific test for this since one that puts together email sending and oda_api is still missing

**Comment by burnout87** [comment]
The current `empty-async` is the one that helps at best in testing the email functionality since it always returns `submitted`.

But it cannot work with oda_api. A quick and simple option would be to build another empty instrument that returns `submitted` a number of times before returning `done`.

Maybe this helps also for other purposes?

**Comment by volodymyrss** [comment]
yeah, maybe. By inheriting, to reduce duplication? Could be useful.
Or it could be the same `empty-async` but bahavior changing depending on the parameters provided. Less code. Also this is quite realistic.

**Comment by burnout87** [comment]
> yeah, maybe. By inheriting, to reduce duplication? Could be useful.
> Or it could be the same `empty-async` but bahavior changing depending on the parameters provided. Less code. Also this is quite realistic.

I am actually inheriting, way faster

**Comment by burnout87** [comment]
Closed with  [https://github.com/oda-hub/dispatcher-app/pull/119](https://github.com/oda-hub/dispatcher-app/pull/119)

**Comment by burnout87** [comment]
Edit looks like I cannot close this
