### ISSUE TITLE
tutorial in readthedocs for viewing mosaic is no more valid

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/oda_api#58]

**Comment by volodymyrss** [comment]
I did not entirely understand which instructions. Could you please clarify?

**Comment by volodymyrss** [comment]
@andriineronov  could you clarify what exactly.

**Comment by andriineronov** [comment]
For the mosaic image: data_collection.mosaic_image_0_mosaic.data_unit[1].data.shape is now showing (4,) instead of the image shape. Perhaps related, the image does not show anymore

#interactive
#%matplotlib notebook

%matplotlib inline
im=OdaImage(data_collection.mosaic_image_0_mosaic)
im.show(unit_ID=1)

**Comment by ferrigno** [comment]
I made the necessary modification.
